### ISSUE TITLE
Simple examples of usage.

### ISSUE THREAD

**Issue by el3ctr0lyte** [Xor-el/CryptoLib4Pascal#24]
Hi Xor-el! I really want to use cryptolib4pascal, but i have no idea how to use it. The unit test a very complicated. Although i think i can figure it by just delving into the unit tests, i think it would be better if you wrote some simpler examples. At the moment it would be just easier to use DCPCrypt but i would not have the flexibility of Cryptolib4pascal.

**Comment by Xor-el** [comment]
There is a usage sample code [here](https://github.com/Xor-el/CryptoLib4Pascal/tree/master/CryptoLib.Samples).
However, since this library is quite versatile, I think the unit tests is the best place to search for examples for what you want to achieve.
If you don't find any sample in the unit tests and you are sure the library supports this, please reach out with such issue and I will be happy to drop a demo for you.
